//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public string DocumentName { get; set; }
        public string DocumentType { get; set; }
        public byte[] Content { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> WorkItemID { get; set; }
        public System.Guid ComponentRef { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FieldMapCode { get; set; }
        public string Extension { get; set; }
        public string URL { get; set; }
    
        public virtual WorkItem WorkItem { get; set; }
    }
}
