//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connections
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemField
    {
        public int ID { get; set; }
        public Nullable<int> WorkItemID { get; set; }
        public string FieldCode { get; set; }
        public string FieldValue { get; set; }
        public string FieldSetCode { get; set; }
        public string MapCode { get; set; }
        public System.Guid ComponentRef { get; set; }
    
        public virtual WorkItem WorkItem { get; set; }
    }
}
