//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incubator.EventManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRole
    {
        public int ID { get; set; }
        public string GroupRole1 { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
