//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incubator.EventManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncubatorQuardrant
    {
        public int IncubatorQuardrantID { get; set; }
        public string IncubatorQuardrantText { get; set; }
        public string IncubatorQuardrantCode { get; set; }
        public Nullable<int> ScoreCardValue { get; set; }
    }
}
