//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incubator.EventManager.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boolean> Booleans { get; set; }
        public virtual DbSet<CalculationMap> CalculationMaps { get; set; }
        public virtual DbSet<Calculation> Calculations { get; set; }
        public virtual DbSet<ClientField> ClientFields { get; set; }
        public virtual DbSet<ClientType> ClientTypes { get; set; }
        public virtual DbSet<DropdownSetMap> DropdownSetMaps { get; set; }
        public virtual DbSet<DropdownSet> DropdownSets { get; set; }
        public virtual DbSet<DropdownValue> DropdownValues { get; set; }
        public virtual DbSet<FieldSetGroupMap> FieldSetGroupMaps { get; set; }
        public virtual DbSet<FieldSetGroup> FieldSetGroups { get; set; }
        public virtual DbSet<FieldSetMap> FieldSetMaps { get; set; }
        public virtual DbSet<FieldSet> FieldSets { get; set; }
        public virtual DbSet<FieldType> FieldTypes { get; set; }
        public virtual DbSet<IncubatorQuardrant> IncubatorQuardrants { get; set; }
        public virtual DbSet<QuardrantMap> QuardrantMaps { get; set; }
        public virtual DbSet<RejectionReason> RejectionReasons { get; set; }
        public virtual DbSet<RequirementMap> RequirementMaps { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<WorkItemStageMap> WorkItemStageMaps { get; set; }
        public virtual DbSet<WorkItemStageReason> WorkItemStageReasons { get; set; }
        public virtual DbSet<WorkItemStage> WorkItemStages { get; set; }
        public virtual DbSet<WorkItemStatu> WorkItemStatus { get; set; }
    }
}
