//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Incubator.EventManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> UserLocked { get; set; }
        public string Salt { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Fullname { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public Nullable<int> GroupID { get; set; }
    }
}
