//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requirements.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DropdownSetMap
    {
        public int ID { get; set; }
        public System.Guid MUID { get; set; }
        public string VersionName { get; set; }
        public int VersionNumber { get; set; }
        public string VersionFlag { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int ChangeTrackingMask { get; set; }
        public string DropdownValue_Code { get; set; }
        public string DropdownValue_Name { get; set; }
        public Nullable<int> DropdownValue_ID { get; set; }
        public string DropdownSet_Code { get; set; }
        public string DropdownSet_Name { get; set; }
        public Nullable<int> DropdownSet_ID { get; set; }
        public Nullable<System.DateTime> EnterDateTime { get; set; }
        public string EnterUserName { get; set; }
        public Nullable<int> EnterVersionNumber { get; set; }
        public Nullable<System.DateTime> LastChgDateTime { get; set; }
        public string LastChgUserName { get; set; }
        public Nullable<int> LastChgVersionNumber { get; set; }
        public string ValidationStatus { get; set; }
        public string FieldSetGroup_Code { get; set; }
        public string FieldSetGroup_Name { get; set; }
        public Nullable<int> FieldSetGroup_ID { get; set; }
        public string ScoreCard { get; set; }
    
        public virtual DropdownSet DropdownSet { get; set; }
        public virtual DropdownValue DropdownValue { get; set; }
    }
}
