//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requirements.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldSetGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldSetGroup()
        {
            this.FieldSetGroupMaps = new HashSet<FieldSetGroupMap>();
            this.RequirementMaps = new HashSet<RequirementMap>();
        }
    
        public int ID { get; set; }
        public Nullable<System.Guid> MUID { get; set; }
        public string VersionName { get; set; }
        public Nullable<int> VersionNumber { get; set; }
        public string VersionFlag { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> ChangeTrackingMask { get; set; }
        public Nullable<System.DateTime> EnterDateTime { get; set; }
        public string EnterUserName { get; set; }
        public Nullable<int> EnterVersionNumber { get; set; }
        public Nullable<System.DateTime> LastChgDateTime { get; set; }
        public string LastChgUserName { get; set; }
        public Nullable<int> LastChgVersionNumber { get; set; }
        public string ValidationStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldSetGroupMap> FieldSetGroupMaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequirementMap> RequirementMaps { get; set; }
    }
}
