//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Requirements.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldSetMap
    {
        public int ID { get; set; }
        public Nullable<System.Guid> MUID { get; set; }
        public string VersionName { get; set; }
        public Nullable<int> VersionNumber { get; set; }
        public string VersionFlag { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> ChangeTrackingMask { get; set; }
        public string Field_Code { get; set; }
        public string Field_Name { get; set; }
        public Nullable<int> Field_ID { get; set; }
        public string DropdownSet_Code { get; set; }
        public string DropdownSet_Name { get; set; }
        public Nullable<int> DropdownSet_ID { get; set; }
        public Nullable<System.DateTime> EnterDateTime { get; set; }
        public string EnterUserName { get; set; }
        public Nullable<int> EnterVersionNumber { get; set; }
        public Nullable<System.DateTime> LastChgDateTime { get; set; }
        public string LastChgUserName { get; set; }
        public Nullable<int> LastChgVersionNumber { get; set; }
        public string ValidationStatus { get; set; }
        public string FieldSet_Code { get; set; }
        public string FieldSet_Name { get; set; }
        public Nullable<int> FieldSetID { get; set; }
        public string ToolTip { get; set; }
        public string FieldOrder { get; set; }
        public string IsRequired_Code { get; set; }
        public string IsRequired_Name { get; set; }
        public Nullable<int> IsRequired_ID { get; set; }
        public string Caculation_Code { get; set; }
        public string Caculation_Name { get; set; }
        public Nullable<int> Caculation_ID { get; set; }
        public string FieldScore { get; set; }
        public string IsRelated_Code { get; set; }
        public string IsRelated_Name { get; set; }
        public Nullable<int> IsRelated_ID { get; set; }
        public string Length { get; set; }
    
        public virtual ClientField ClientField { get; set; }
        public virtual FieldSet FieldSet { get; set; }
    }
}
