//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefate.Incubator.WorkItem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncubatorQuarter
    {
        public string Quarder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> WorkItemID { get; set; }
        public Nullable<int> IncubatorQuardrantID { get; set; }
        public int IncubatorQuarterID { get; set; }
        public Nullable<int> ScoreCardValue { get; set; }
    }
}
