//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefate.Incubator.WorkItem.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IncubatorClientsEntities : DbContext
    {
        public IncubatorClientsEntities()
            : base("name=IncubatorClientsEntities")
        {
        }
    
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<ClientType> ClientTypes { get; set; }
        public virtual DbSet<CompanyUser> CompanyUsers { get; set; }
        public virtual DbSet<ComponentChangeType> ComponentChangeTypes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<GroupRole> GroupRoles { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WorkItemField> WorkItemFields { get; set; }
        public virtual DbSet<WorkItemStatu> WorkItemStatus { get; set; }
        public virtual DbSet<WorkItem> WorkItems { get; set; }
        public virtual DbSet<WorkItemStage> WorkItemStages { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<IncubatorQuardrant> IncubatorQuardrants { get; set; }
        public virtual DbSet<Milestone> Milestones { get; set; }
        public virtual DbSet<IncubatorQuarter> IncubatorQuarters { get; set; }
        public virtual DbSet<IncubationStage> IncubationStages { get; set; }
        public virtual DbSet<WorkItemIncubationComment> WorkItemIncubationComments { get; set; }
        public virtual DbSet<WorkItemIncubationStage> WorkItemIncubationStages { get; set; }
        public virtual DbSet<CommentPriority> CommentPriorities { get; set; }
        public virtual DbSet<EventInvitation> EventInvitations { get; set; }
        public virtual DbSet<IncubatorEvent> IncubatorEvents { get; set; }
        public virtual DbSet<WorkItemTimeLine> WorkItemTimeLines { get; set; }
        public virtual DbSet<EventGuest> EventGuests { get; set; }
        public virtual DbSet<VarificationNumber> VarificationNumbers { get; set; }
        public virtual DbSet<DocumentReviewStatu> DocumentReviewStatus { get; set; }
        public virtual DbSet<DocumentStatu> DocumentStatus { get; set; }
        public virtual DbSet<WorkItemDocumentStatu> WorkItemDocumentStatus { get; set; }
        public virtual DbSet<CommentRecomendation> CommentRecomendations { get; set; }
        public virtual DbSet<InterventionReportTemplate> InterventionReportTemplates { get; set; }
        public virtual DbSet<InterventionReport> InterventionReports { get; set; }
        public virtual DbSet<InterventionReportField> InterventionReportFields { get; set; }
    }
}
