//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sefate.Incubator.WorkItem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemTimeLine
    {
        public int ID { get; set; }
        public Nullable<int> IncubationStageID { get; set; }
        public Nullable<int> WorkItemID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int WorkItemStageID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
